spring:
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/mydatabase?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.postgresql.Driver

